server:
  port: 8080
  servlet:
    context-path: /marketing
  compression:
    enabled: true
    min-response-size: 1000

logging:
  level:
    com:
      zhongmei:
        yunfu: debug
  file: ./out/zhongmei_log.log